package golang

import "github.com/KEN3pei/jev-tools/go-intent-analyzer/analyzer/questions"

const Language = "go"
const Task = "Infer deliberate design intent from the supplied Go evidence. Absence of evidence is insufficient, not evidence that an intent is absent. Judge intent only; do not grade implementation quality."

var Definitions = []questions.Definition{
	{ID: "simplicity", Instruction: "Determine whether the Go evidence supports a deliberate intent to prioritize simplicity: a small API, direct control flow, few moving parts, or an explicit decision not to generalize. Ordinary short code alone is not enough; look for corroboration in comments, tests, surrounding declarations, or history.", Keywords: []string{"simple", "simplify", "minimal", "straightforward"}},
	{ID: "change_localization", Instruction: "Determine whether the Go evidence supports a deliberate intent to localize an anticipated kind of change behind a stable boundary. Relevant signals include consumer-owned narrow interfaces, internal packages, adapters, and callers depending on a stable contract. An interface by itself is not enough; identify the anticipated change and evidence that the boundary contains it.", Keywords: []string{"isolate", "boundary", "encapsulate", "decouple"}},
	{ID: "extensibility", Instruction: "Determine whether the Go evidence supports a deliberate intent to add implementations, behaviors, or variants without modifying established code. Relevant signals include multiple implementations, registration, strategies, factories, or tests adding variants. Do not infer this intent from an interface or function value alone.", Keywords: []string{"extend", "plugin", "interface", "strategy", "variant"}},
	{ID: "reliability", Instruction: "Determine whether the Go evidence supports a deliberate intent to handle failures and preserve service behavior. Relevant signals include context cancellation, bounded timeouts, explicit retry policy, idempotency, partial-failure handling, fallback, and recovery tests. Routine error propagation alone is not enough.", Keywords: []string{"retry", "timeout", "recover", "idempot", "fallback"}},
	{ID: "performance", Instruction: "Determine whether the Go evidence supports a deliberate performance intent involving allocation, CPU, I/O, latency, throughput, batching, caching, pooling, or concurrency. Require evidence of a conscious tradeoff such as a benchmark, comment, specialized data structure, reuse, or history; goroutines or preallocation alone are weak evidence.", Keywords: []string{"performance", "latency", "allocation", "cache", "pool", "batch", "concurrent", "benchmark"}},
	{ID: "security", Instruction: "Determine whether the Go evidence supports a deliberate security intent at a trust boundary. Relevant signals include authentication or authorization, validation of untrusted input, path or query restrictions, secret handling, cryptographic checks, and adversarial tests. Generic validation or returning an error alone is not enough.", Keywords: []string{"security", "authorize", "permission", "validate", "sanitize", "secret", "token", "credential"}},
	{ID: "backward_compatibility", Instruction: "Determine whether the Go evidence supports a deliberate intent to preserve existing caller contracts, wire formats, stored data, or API behavior while evolving code. Relevant signals include deprecated adapters, version handling, legacy-format tests, aliases, and compatibility-focused history. A stable exported name alone is not enough.", Keywords: []string{"compat", "legacy", "deprecated", "existing client", "old format", "version"}},
	{ID: "testability", Instruction: "Determine whether the Go evidence supports a deliberate intent to make behavior controllable and observable in tests. Relevant signals include narrow dependency injection, deterministic clocks or randomness, side-effect seams, fakes, and contract tests. Merely having tests or interfaces is not enough.", Keywords: []string{"testable", "fake", "stub", "deterministic", "inject", "clock"}},
	{ID: "operability", Instruction: "Determine whether the Go evidence supports a deliberate intent to make production behavior observable, configurable, diagnosable, or recoverable. Relevant signals include structured logs, metrics, tracing, health checks, runtime configuration, diagnostic context, and operational tests. Incidental logging alone is weak evidence.", Keywords: []string{"metric", "trace", "log", "diagnos", "health", "config", "observe"}},
	{ID: "migration_safety", Instruction: "Determine whether the Go evidence supports a deliberate intent to make a change deployable in stages or reversible. Relevant signals include dual read or write paths, feature gates, backfills, old/new coexistence, checkpointing, rollout, and rollback handling. General backward compatibility alone is not enough.", Keywords: []string{"migrat", "rollback", "rollout", "dual", "backfill", "coexist", "feature flag"}},
	{ID: "delivery_speed", Instruction: "Determine whether comments, tests, code structure, or history support a deliberate intent to obtain early feedback or deliver quickly while knowingly limiting completeness or generality. Explicit prototype, temporary, MVP, TODO, or follow-up language is relevant. Rough or low-quality code alone must not be treated as delivery-speed intent.", Keywords: []string{"temporary", "prototype", "quick", "follow-up", "todo", "mvp"}},
}

var Questions = questions.Build(Definitions)
