package generate

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/KEN3pei/jev-tools/jevgen/internal/schema"
)

func Go(set schema.QuestionSet, packageName string) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("package name is required")
	}
	hash, err := set.Hash()
	if err != nil {
		return nil, err
	}
	questionsJSON, err := json.Marshal(set.Questions)
	if err != nil {
		return nil, err
	}
	ids := sortedQuestionIDs(set)
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by jevgen. DO NOT EDIT.\n\npackage %s\n\n", packageName)
	out.WriteString("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n\n")
	fmt.Fprintf(&out, "const QuestionSetName = %q\n", set.Name)
	fmt.Fprintf(&out, "const SchemaVersion = %q\n", set.SchemaVersion)
	fmt.Fprintf(&out, "const SchemaHash = %q\n\n", hash)
	out.WriteString(`type Question struct {
	Type string ` + "`json:\"type\"`" + `
	Instructions string ` + "`json:\"instructions\"`" + `
	Criteria any ` + "`json:\"criteria,omitempty\"`" + `
}

type ChoiceAnswer[T ~string] struct {
	Type string ` + "`json:\"type\"`" + `
	Choice T ` + "`json:\"choice\"`" + `
	Confidence float64 ` + "`json:\"confidence,omitempty\"`" + `
	Probabilities map[string]float64 ` + "`json:\"probabilities,omitempty\"`" + `
}

type ScoreAnswer struct {
	Type string ` + "`json:\"type\"`" + `
	Score float64 ` + "`json:\"score\"`" + `
	Confidence float64 ` + "`json:\"confidence,omitempty\"`" + `
}

type NoulAnswer struct {
	Type string ` + "`json:\"type\"`" + `
	Noul float64 ` + "`json:\"noul\"`" + `
}

`)
	for _, id := range ids {
		question := set.Questions[id]
		if question.Type != "choice" {
			continue
		}
		typeName := exported(id)
		fmt.Fprintf(&out, "type %sChoice string\n\nconst (\n", typeName)
		criteria, _ := question.ChoiceCriteria()
		values := make([]string, 0, len(criteria))
		for value := range criteria {
			values = append(values, value)
		}
		sort.Strings(values)
		for _, value := range values {
			fmt.Fprintf(&out, "\t%sChoice%s %sChoice = %q\n", typeName, exported(value), typeName, value)
		}
		out.WriteString(")\n\n")
	}
	out.WriteString("type Answers struct {\n")
	for _, id := range ids {
		question := set.Questions[id]
		field := exported(id)
		answerType := "NoulAnswer"
		switch question.Type {
		case "choice":
			answerType = fmt.Sprintf("ChoiceAnswer[%sChoice]", field)
		case "score":
			answerType = "ScoreAnswer"
		}
		fmt.Fprintf(&out, "\t%s %s `json:\"%s\"`\n", field, answerType, id)
	}
	out.WriteString("}\n\n")
	fmt.Fprintf(&out, "var questionsJSON = []byte(%q)\n\n", questionsJSON)
	out.WriteString(`func Questions() map[string]Question {
	var questions map[string]Question
	if err := json.Unmarshal(questionsJSON, &questions); err != nil {
		panic(err)
	}
	return questions
}
`)
	out.WriteString("\nfunc DecodeAnswers(data []byte) (Answers, error) {\n")
	out.WriteString("\tvar raw map[string]json.RawMessage\n")
	out.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil { return Answers{}, err }\n")
	for _, id := range ids {
		fmt.Fprintf(&out, "\tif _, ok := raw[%q]; !ok { return Answers{}, fmt.Errorf(\"missing answer %%q\", %q) }\n", id, id)
	}
	out.WriteString("\tvar answers Answers\n")
	out.WriteString("\tif err := json.Unmarshal(data, &answers); err != nil { return Answers{}, err }\n")
	for _, id := range ids {
		question := set.Questions[id]
		switch question.Type {
		case "score":
			fmt.Fprintf(&out, "\tif !answerHasField(raw[%q], \"score\") { return Answers{}, fmt.Errorf(\"answer %%q is missing score\", %q) }\n", id, id)
		case "noul":
			fmt.Fprintf(&out, "\tif !answerHasField(raw[%q], \"noul\") { return Answers{}, fmt.Errorf(\"answer %%q is missing noul\", %q) }\n", id, id)
		case "choice":
			field := exported(id)
			criteria, _ := question.ChoiceCriteria()
			values := make([]string, 0, len(criteria))
			for value := range criteria {
				values = append(values, value)
			}
			sort.Strings(values)
			fmt.Fprintf(&out, "\tswitch answers.%s.Choice {\n", field)
			out.WriteString("\tcase ")
			for index, value := range values {
				if index > 0 {
					out.WriteString(", ")
				}
				fmt.Fprintf(&out, "%sChoice%s", field, exported(value))
			}
			out.WriteString(":\n")
			fmt.Fprintf(&out, "\tdefault: return Answers{}, fmt.Errorf(\"invalid choice for %s: %%q\", answers.%s.Choice)\n", id, field)
			out.WriteString("\t}\n")
		}
	}
	out.WriteString("\treturn answers, nil\n}\n\n")
	out.WriteString("func answerHasField(data []byte, field string) bool {\n")
	out.WriteString("\tvar raw map[string]json.RawMessage\n")
	out.WriteString("\tif json.Unmarshal(data, &raw) != nil { return false }\n")
	out.WriteString("\t_, ok := raw[field]\n\treturn ok\n}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w\n%s", err, out.String())
	}
	return formatted, nil
}

func sortedQuestionIDs(set schema.QuestionSet) []string {
	ids := make([]string, 0, len(set.Questions))
	for id := range set.Questions {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

func exported(value string) string {
	parts := strings.Split(value, "_")
	for index, part := range parts {
		runes := []rune(part)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}
